// Recipe Data for FlavorVerse

const categories = [
  {
    id: '1',
    name: 'Breakfast Recipes',
    description: 'Start your day with delicious breakfast ideas',
    image: 'https://images.unsplash.com/photo-1648726444913-b9dc0afe7d57?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkZWxpY2lvdXMlMjBmb29kJTIwYnJlYWtmYXN0fGVufDF8fHx8MTc2OTE3NjkyNXww&ixlib=rb-4.1.0&q=80&w=1080',
    slug: 'breakfast',
  },
  {
    id: '2',
    name: 'Lunch Recipes',
    description: 'Perfect midday meals for any occasion',
    image: 'https://images.unsplash.com/photo-1676300184761-92585b329535?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxnb3VybWV0JTIwbHVuY2glMjBtZWFsfGVufDF8fHx8MTc2OTE3NjkyNXww&ixlib=rb-4.1.0&q=80&w=1080',
    slug: 'lunch',
  },
  {
    id: '3',
    name: 'Dinner Recipes',
    description: 'Hearty evening meals for the whole family',
    image: 'https://images.unsplash.com/photo-1641834992266-0524e539220a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkaW5uZXIlMjBmb29kJTIwcGxhdGV8ZW58MXx8fHwxNzY5MTc2OTI1fDA&ixlib=rb-4.1.0&q=80&w=1080',
    slug: 'dinner',
  },
  {
    id: '4',
    name: 'Desserts',
    description: 'Sweet treats and indulgent delights',
    image: 'https://images.unsplash.com/photo-1759426016293-1b8be5849a72?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkZXNzZXJ0JTIwc3dlZXQlMjBjYWtlfGVufDF8fHx8MTc2OTE3NjkyNnww&ixlib=rb-4.1.0&q=80&w=1080',
    slug: 'desserts',
  },
  {
    id: '5',
    name: 'Healthy Recipes',
    description: 'Nutritious and delicious healthy meals',
    image: 'https://images.unsplash.com/photo-1624340209404-4f479dd59708?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoZWFsdGh5JTIwc2FsYWQlMjBib3dsfGVufDF8fHx8MTc2OTE0MzQ2OHww&ixlib=rb-4.1.0&q=80&w=1080',
    slug: 'healthy',
  },
  {
    id: '6',
    name: 'Vegetarian & Vegan',
    description: 'Plant-based recipes full of flavor',
    image: 'https://images.unsplash.com/photo-1512398975429-6ec18e1f3eb4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx2ZWdldGFyaWFuJTIwdmVnYW4lMjBmb29kfGVufDF8fHx8MTc2OTE3NjkyN3ww&ixlib=rb-4.1.0&q=80&w=1080',
    slug: 'vegetarian-vegan',
  },
  {
    id: '7',
    name: 'International Cuisine',
    description: 'Explore flavors from around the world',
    image: 'https://images.unsplash.com/photo-1741874299706-2b8e16839aaa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxpbnRlcm5hdGlvbmFsJTIwY3Vpc2luZXxlbnwxfHx8fDE3NjkxNzY5Mjd8MA&ixlib=rb-4.1.0&q=80&w=1080',
    slug: 'international',
  },
];

const recipes = [
  {
    id: '1',
    title: 'Classic Pancakes',
    description: 'Fluffy, golden pancakes perfect for a weekend breakfast',
    image: 'https://images.unsplash.com/photo-1648726444913-b9dc0afe7d57?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkZWxpY2lvdXMlMjBmb29kJTIwYnJlYWtmYXN0fGVufDF8fHx8MTc2OTE3NjkyNXww&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'breakfast',
    prepTime: '10 mins',
    cookTime: '15 mins',
    servings: 4,
    difficulty: 'Easy',
    ingredients: [
      '2 cups all-purpose flour',
      '2 tablespoons sugar',
      '2 teaspoons baking powder',
      '1 teaspoon salt',
      '2 eggs',
      '1 3/4 cups milk',
      '1/4 cup melted butter',
    ],
    instructions: [
      'In a large bowl, whisk together flour, sugar, baking powder, and salt.',
      'In another bowl, beat eggs and add milk and melted butter.',
      'Pour the wet ingredients into the dry ingredients and mix until just combined.',
      'Heat a griddle over medium heat and lightly grease.',
      'Pour 1/4 cup batter for each pancake and cook until bubbles form.',
      'Flip and cook until golden brown on both sides.',
    ],
    tips: [
      'Don\'t overmix the batter - lumps are okay!',
      'Let the batter rest for 5 minutes before cooking.',
      'Use a non-stick pan or griddle for best results.',
    ],
  },
  {
    id: '2',
    title: 'Gourmet Salmon Bowl',
    description: 'A nutritious and delicious salmon bowl with fresh vegetables',
    image: 'https://images.unsplash.com/photo-1676300184761-92585b329535?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxnb3VybWV0JTIwbHVuY2glMjBtZWFsfGVufDF8fHx8MTc2OTE3NjkyNXww&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'lunch',
    prepTime: '15 mins',
    cookTime: '20 mins',
    servings: 2,
    difficulty: 'Medium',
    ingredients: [
      '2 salmon fillets',
      '2 cups cooked quinoa',
      '1 avocado, sliced',
      '1 cup cherry tomatoes',
      '2 cups mixed greens',
      'Lemon juice',
      'Olive oil',
      'Salt and pepper',
    ],
    instructions: [
      'Season salmon with salt, pepper, and lemon juice.',
      'Grill or pan-sear salmon for 4-5 minutes per side.',
      'Prepare quinoa according to package instructions.',
      'Assemble bowls with quinoa, greens, tomatoes, and avocado.',
      'Top with cooked salmon and drizzle with olive oil.',
    ],
    tips: [
      'Don\'t overcook the salmon - it should be slightly pink in the center.',
      'You can substitute brown rice for quinoa.',
      'Add your favorite vegetables for more variety.',
    ],
  },
  {
    id: '3',
    title: 'Herb-Roasted Chicken',
    description: 'Tender roasted chicken with aromatic herbs',
    image: 'https://images.unsplash.com/photo-1641834992266-0524e539220a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkaW5uZXIlMjBmb29kJTIwcGxhdGV8ZW58MXx8fHwxNzY5MTc2OTI1fDA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'dinner',
    prepTime: '15 mins',
    cookTime: '1 hour',
    servings: 6,
    difficulty: 'Medium',
    ingredients: [
      '1 whole chicken (4-5 lbs)',
      '4 tablespoons butter, softened',
      '2 tablespoons fresh rosemary',
      '2 tablespoons fresh thyme',
      '4 garlic cloves, minced',
      'Salt and black pepper',
      '1 lemon, halved',
    ],
    instructions: [
      'Preheat oven to 425°F (220°C).',
      'Mix butter with herbs and garlic.',
      'Pat chicken dry and season inside and out with salt and pepper.',
      'Rub herb butter under the skin and on the outside.',
      'Place lemon halves inside the cavity.',
      'Roast for 1-1.5 hours until golden and cooked through.',
    ],
    tips: [
      'Let the chicken rest for 10-15 minutes before carving.',
      'Use a meat thermometer - internal temp should be 165°F.',
      'Save the pan juices for a delicious gravy.',
    ],
  },
  {
    id: '4',
    title: 'Chocolate Lava Cake',
    description: 'Decadent chocolate cake with a molten center',
    image: 'https://images.unsplash.com/photo-1759426016293-1b8be5849a72?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkZXNzZXJ0JTIwc3dlZXQlMjBjYWtlfGVufDF8fHx8MTc2OTE3NjkyNnww&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'desserts',
    prepTime: '15 mins',
    cookTime: '12 mins',
    servings: 4,
    difficulty: 'Medium',
    ingredients: [
      '6 oz dark chocolate',
      '1/2 cup butter',
      '2 eggs',
      '2 egg yolks',
      '1/4 cup sugar',
      '2 tablespoons flour',
      'Butter and cocoa for ramekins',
    ],
    instructions: [
      'Preheat oven to 425°F (220°C).',
      'Butter and dust ramekins with cocoa powder.',
      'Melt chocolate and butter together.',
      'Whisk eggs, yolks, and sugar until thick.',
      'Fold in melted chocolate and flour.',
      'Pour into ramekins and bake for 12-14 minutes.',
    ],
    tips: [
      'Serve immediately for the best molten center.',
      'Top with vanilla ice cream or whipped cream.',
      'The center should be slightly jiggly when done.',
    ],
  },
  {
    id: '5',
    title: 'Rainbow Veggie Bowl',
    description: 'Colorful and nutritious vegetable bowl',
    image: 'https://images.unsplash.com/photo-1624340209404-4f479dd59708?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoZWFsdGh5JTIwc2FsYWQlMjBib3dsfGVufDF8fHx8MTc2OTE0MzQ2OHww&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'healthy',
    prepTime: '20 mins',
    cookTime: '10 mins',
    servings: 2,
    difficulty: 'Easy',
    ingredients: [
      '2 cups mixed greens',
      '1 cup roasted chickpeas',
      '1 cup roasted sweet potato',
      '1/2 cup shredded carrots',
      '1/2 cup red cabbage',
      '1 avocado',
      'Tahini dressing',
    ],
    instructions: [
      'Roast chickpeas and sweet potato until crispy.',
      'Prepare all vegetables and arrange in bowls.',
      'Top with avocado slices.',
      'Drizzle with tahini dressing.',
      'Season with salt, pepper, and lemon juice.',
    ],
    tips: [
      'Meal prep the roasted vegetables ahead of time.',
      'Add your favorite protein for extra nutrition.',
      'Mix and match seasonal vegetables.',
    ],
  },
  {
    id: '6',
    title: 'Vegan Buddha Bowl',
    description: 'Plant-based power bowl packed with nutrients',
    image: 'https://images.unsplash.com/photo-1512398975429-6ec18e1f3eb4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx2ZWdldGFyaWFuJTIwdmVnYW4lMjBmb29kfGVufDF8fHx8MTc2OTE3NjkyN3ww&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'vegetarian-vegan',
    prepTime: '25 mins',
    cookTime: '30 mins',
    servings: 3,
    difficulty: 'Easy',
    ingredients: [
      '1 cup quinoa',
      '2 cups kale',
      '1 cup roasted broccoli',
      '1 cup baked tofu',
      '1/4 cup hummus',
      'Hemp seeds',
      'Lemon tahini dressing',
    ],
    instructions: [
      'Cook quinoa according to package directions.',
      'Bake marinated tofu until golden.',
      'Roast broccoli with olive oil and spices.',
      'Massage kale with a bit of dressing.',
      'Assemble bowls and top with hummus and hemp seeds.',
    ],
    tips: [
      'Press tofu before marinating for best texture.',
      'Massaging kale makes it tender and easier to digest.',
      'Store components separately for meal prep.',
    ],
  },
  {
    id: '7',
    title: 'Authentic Pad Thai',
    description: 'Classic Thai noodle dish with tangy tamarind sauce',
    image: 'https://images.unsplash.com/photo-1741874299706-2b8e16839aaa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxpbnRlcm5hdGlvbmFsJTIwY3Vpc2luZXxlbnwxfHx8fDE3NjkxNzY5Mjd8MA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'international',
    prepTime: '20 mins',
    cookTime: '15 mins',
    servings: 4,
    difficulty: 'Medium',
    ingredients: [
      '8 oz rice noodles',
      '3 tablespoons tamarind paste',
      '2 tablespoons fish sauce',
      '2 tablespoons sugar',
      '2 eggs',
      '1 cup bean sprouts',
      'Peanuts and lime wedges',
      '3 cloves garlic',
    ],
    instructions: [
      'Soak rice noodles in warm water until soft.',
      'Mix tamarind, fish sauce, and sugar for the sauce.',
      'Stir-fry garlic, then add beaten eggs.',
      'Add drained noodles and sauce, tossing to combine.',
      'Add bean sprouts and garnish with peanuts and lime.',
    ],
    tips: [
      'Don\'t oversoak the noodles - they should be pliable.',
      'High heat is key for authentic wok flavor.',
      'Serve immediately for best texture.',
    ],
  },
  {
    id: '8',
    title: 'Mediterranean Chickpea Salad',
    description: 'Fresh and vibrant salad with Mediterranean flavors',
    image: 'https://images.unsplash.com/photo-1624340209404-4f479dd59708?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoZWFsdGh5JTIwc2FsYWQlMjBib3dsfGVufDF8fHx8MTc2OTE0MzQ2OHww&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'lunch',
    prepTime: '15 mins',
    cookTime: '0 mins',
    servings: 4,
    difficulty: 'Easy',
    ingredients: [
      '2 cans chickpeas, drained',
      '1 cup cherry tomatoes',
      '1 cucumber, diced',
      '1/2 red onion, sliced',
      '1/4 cup kalamata olives',
      'Feta cheese',
      'Olive oil and lemon juice',
      'Fresh herbs',
    ],
    instructions: [
      'Combine chickpeas, tomatoes, cucumber, and onion.',
      'Add olives and crumbled feta.',
      'Whisk together olive oil, lemon juice, and herbs.',
      'Pour dressing over salad and toss gently.',
      'Let sit for 10 minutes before serving.',
    ],
    tips: [
      'This salad gets better as it sits - great for meal prep!',
      'Add grilled chicken or shrimp for extra protein.',
      'Use fresh herbs like parsley and mint for authentic flavor.',
    ],
  },
  {
    id: '9',
    title: 'Blueberry Muffins',
    description: 'Moist and fluffy muffins bursting with blueberries',
    image: 'https://images.unsplash.com/photo-1648726444913-b9dc0afe7d57?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkZWxpY2lvdXMlMjBmb29kJTIwYnJlYWtmYXN0fGVufDF8fHx8MTc2OTE3NjkyNXww&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'breakfast',
    prepTime: '15 mins',
    cookTime: '25 mins',
    servings: 12,
    difficulty: 'Easy',
    ingredients: [
      '2 cups all-purpose flour',
      '3/4 cup sugar',
      '2 teaspoons baking powder',
      '1/2 teaspoon salt',
      '1/3 cup vegetable oil',
      '1 egg',
      '1 cup milk',
      '1 1/2 cups fresh blueberries',
    ],
    instructions: [
      'Preheat oven to 400°F (200°C).',
      'Mix flour, sugar, baking powder, and salt.',
      'In another bowl, combine oil, egg, and milk.',
      'Fold wet ingredients into dry until just combined.',
      'Gently fold in blueberries.',
      'Fill muffin cups and bake for 20-25 minutes.',
    ],
    tips: [
      'Toss blueberries in flour before adding to prevent sinking.',
      'Don\'t overmix the batter - it should be lumpy.',
      'These freeze beautifully for quick breakfasts.',
    ],
  },
];

const blogPosts = [
  {
    id: '1',
    title: '10 Quick Dinner Recipes for Busy Days',
    excerpt: 'Short on time? These delicious dinner recipes can be made in 30 minutes or less, perfect for busy weeknights.',
    image: 'https://images.unsplash.com/photo-1617735605078-8a9336be0816?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb29raW5nJTIwaW5ncmVkaWVudHMlMjBraXRjaGVufGVufDF8fHx8MTc2OTE3NjkyOHww&ixlib=rb-4.1.0&q=80&w=1080',
    date: 'January 20, 2026',
    author: 'Chef Maria',
  },
  {
    id: '2',
    title: 'Healthy Eating Made Easy',
    excerpt: 'Discover simple tips and tricks to make healthy eating a sustainable and enjoyable part of your lifestyle.',
    image: 'https://images.unsplash.com/photo-1624340209404-4f479dd59708?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoZWFsdGh5JTIwc2FsYWQlMjBib3dsfGVufDF8fHx8MTc2OTE0MzQ2OHww&ixlib=rb-4.1.0&q=80&w=1080',
    date: 'January 18, 2026',
    author: 'Nutritionist Sarah',
  },
  {
    id: '3',
    title: 'Cooking Tips for Beginners',
    excerpt: 'New to cooking? Start your culinary journey with these essential tips and techniques that every beginner should know.',
    image: 'https://images.unsplash.com/photo-1617735605078-8a9336be0816?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb29raW5nJTIwaW5ncmVkaWVudHMlMjBraXRjaGVufGVufDF8fHx8MTc2OTE3NjkyOHww&ixlib=rb-4.1.0&q=80&w=1080',
    date: 'January 15, 2026',
    author: 'Chef Alex',
  },
];

const heroSlides = [
  {
    id: 1,
    image: 'https://images.unsplash.com/photo-1641834992266-0524e539220a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkaW5uZXIlMjBmb29kJTIwcGxhdGV8ZW58MXx8fHwxNzY5MTc2OTI1fDA&ixlib=rb-4.1.0&q=80&w=1080',
    title: 'Cook Delicious Recipes Every Day',
    description: 'Discover thousands of tested recipes from around the world',
  },
  {
    id: 2,
    image: 'https://images.unsplash.com/photo-1617735605078-8a9336be0816?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb29raW5nJTIwaW5ncmVkaWVudHMlMjBraXRjaGVufGVufDF8fHx8MTc2OTE3NjkyOHww&ixlib=rb-4.1.0&q=80&w=1080',
    title: 'Easy, Tasty & Tested Recipes',
    description: 'Step-by-step instructions that guarantee success',
  },
  {
    id: 3,
    image: 'https://images.unsplash.com/photo-1759426016293-1b8be5849a72?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkZXNzZXJ0JTIwc3dlZXQlMjBjYWtlfGVufDF8fHx8MTc2OTE3NjkyNnww&ixlib=rb-4.1.0&q=80&w=1080',
    title: 'For Everyone',
    description: 'From beginners to experienced chefs, we have recipes for all skill levels',
  },
];
